--------------------------------------------------------
--  文件已创建 - 星期五-四月-14-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUSINESSORDINAL
--------------------------------------------------------

  CREATE TABLE "CITY"."BUSINESSORDINAL" 
   (	"BUSINESSDATE" VARCHAR2(10 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"ORDINAL" NUMBER(*,0), 
	"COUNTYCODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CITY.BUSINESSORDINAL
SET DEFINE OFF;
Insert into CITY.BUSINESSORDINAL (BUSINESSDATE,CATEGORY,ORDINAL,COUNTYCODE) values ('2017/4/13','cars',2,'haiyang');
--------------------------------------------------------
--  DDL for Index BUSINESSORDINAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."BUSINESSORDINAL_PK" ON "CITY"."BUSINESSORDINAL" ("CATEGORY", "COUNTYCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUSINESSORDINAL
--------------------------------------------------------

  ALTER TABLE "CITY"."BUSINESSORDINAL" ADD CONSTRAINT "BUSINESSORDINAL_PK" PRIMARY KEY ("CATEGORY", "COUNTYCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CITY"."BUSINESSORDINAL" MODIFY ("COUNTYCODE" NOT NULL ENABLE);
  ALTER TABLE "CITY"."BUSINESSORDINAL" MODIFY ("ORDINAL" NOT NULL ENABLE);
  ALTER TABLE "CITY"."BUSINESSORDINAL" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "CITY"."BUSINESSORDINAL" MODIFY ("BUSINESSDATE" NOT NULL ENABLE);
