--------------------------------------------------------
--  文件已创建 - 星期五-四月-28-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUSINESSCATEGORY
--------------------------------------------------------

  CREATE TABLE "CITY"."BUSINESSCATEGORY" 
   (	"BUSINESSCODE" VARCHAR2(20 BYTE), 
	"BUSINESSNAME" VARCHAR2(20 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"SERVICEAPI" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CITY.BUSINESSCATEGORY
SET DEFINE OFF;
Insert into CITY.BUSINESSCATEGORY (BUSINESSCODE,BUSINESSNAME,CATEGORY,SERVICEAPI) values ('1','换证-期满换证','drivers','huanzhengqimanhuanzheng');
--------------------------------------------------------
--  DDL for Index BUSINESSCATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."BUSINESSCATEGORY_PK" ON "CITY"."BUSINESSCATEGORY" ("BUSINESSCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUSINESSCATEGORY
--------------------------------------------------------

  ALTER TABLE "CITY"."BUSINESSCATEGORY" MODIFY ("BUSINESSCODE" NOT NULL ENABLE);
  ALTER TABLE "CITY"."BUSINESSCATEGORY" MODIFY ("BUSINESSNAME" NOT NULL ENABLE);
  ALTER TABLE "CITY"."BUSINESSCATEGORY" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "CITY"."BUSINESSCATEGORY" MODIFY ("SERVICEAPI" NOT NULL ENABLE);
  ALTER TABLE "CITY"."BUSINESSCATEGORY" ADD CONSTRAINT "BUSINESSCATEGORY_PK" PRIMARY KEY ("BUSINESSCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
