--------------------------------------------------------
--  文件已创建 - 星期五-四月-14-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARINFOR
--------------------------------------------------------

  CREATE TABLE "CITY"."CARINFOR" 
   (	"ID" NUMBER, 
	"CAR_NUM" VARCHAR2(50 BYTE), 
	"BRAND" VARCHAR2(50 BYTE), 
	"MODEL_TYPE" VARCHAR2(50 BYTE), 
	"VIN" VARCHAR2(50 BYTE), 
	"PLATE_TYPE" VARCHAR2(30 BYTE), 
	"OWNER" VARCHAR2(20 BYTE), 
	"OWNER_ID" VARCHAR2(20 BYTE), 
	"CAR_LENGTH" NUMBER(3,3), 
	"CAR_WIDTH" NUMBER(3,3), 
	"CAR_HEIGHT" NUMBER(3,3), 
	"STANDARD_LENGTH" NUMBER(3,3), 
	"STANDARD_WIDTH" NUMBER(3,3), 
	"STANDARD_HEIGHT" NUMBER(3,3), 
	"QUEUE_NUM" VARCHAR2(10 BYTE), 
	"TIME" DATE, 
	"SERIAL_NUM" VARCHAR2(20 BYTE), 
	"FINISH" NUMBER, 
	"TASK_TYPE" NUMBER DEFAULT 0, 
	"INSPECTOR" VARCHAR2(50 BYTE), 
	"RECHECKER" VARCHAR2(50 BYTE), 
	"UNLOAD_TASK_NUM" VARCHAR2(15 BYTE), 
	"INVALID_TASK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CITY.CARINFOR
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CARINFOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."CARINFOR_PK" ON "CITY"."CARINFOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CARINFOR
--------------------------------------------------------

  ALTER TABLE "CITY"."CARINFOR" ADD CONSTRAINT "CARINFOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CITY"."CARINFOR" MODIFY ("ID" NOT NULL ENABLE);
