--------------------------------------------------------
--  文件已创建 - 星期五-四月-28-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CORPORATEINFO
--------------------------------------------------------

  CREATE TABLE "CITY"."CORPORATEINFO" 
   (	"CODE" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CITY.CORPORATEINFO
SET DEFINE OFF;
Insert into CITY.CORPORATEINFO (CODE,NAME,ADDRESS) values ('123','gong si 1','di zhi79876867867');
Insert into CITY.CORPORATEINFO (CODE,NAME,ADDRESS) values ('gongsi1','name1','dizhi1');
Insert into CITY.CORPORATEINFO (CODE,NAME,ADDRESS) values ('gongs3i1','name1','dizhi1');
Insert into CITY.CORPORATEINFO (CODE,NAME,ADDRESS) values ('gongsi12','name12','diz22hi1');
--------------------------------------------------------
--  DDL for Index CORPORATEINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."CORPORATEINFO_PK" ON "CITY"."CORPORATEINFO" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CORPORATEINFO
--------------------------------------------------------

  ALTER TABLE "CITY"."CORPORATEINFO" ADD CONSTRAINT "CORPORATEINFO_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CITY"."CORPORATEINFO" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CITY"."CORPORATEINFO" MODIFY ("CODE" NOT NULL ENABLE);
