--------------------------------------------------------
--  文件已创建 - 星期五-五月-26-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CORPORATEINFO
--------------------------------------------------------

  CREATE TABLE "CITY"."CORPORATEINFO" 
   (	"CODE" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"PHONENUMBER" VARCHAR2(50 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CORPORATEINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."CORPORATEINFO_PK" ON "CITY"."CORPORATEINFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CORPORATEINFO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CITY"."CORPORATEINFO_TRG" 
BEFORE INSERT ON CORPORATEINFO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CORPORATEINFO_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CITY"."CORPORATEINFO_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CORPORATEINFO
--------------------------------------------------------

  ALTER TABLE "CITY"."CORPORATEINFO" ADD CONSTRAINT "CORPORATEINFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CITY"."CORPORATEINFO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CITY"."CORPORATEINFO" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CITY"."CORPORATEINFO" MODIFY ("CODE" NOT NULL ENABLE);
