--------------------------------------------------------
--  文件已创建 - 星期一-六月-12-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ONLINERECORD
--------------------------------------------------------

  CREATE TABLE "CITY"."ONLINERECORD" 
   (	"IDENTITY" VARCHAR2(20 BYTE), 
	"RECORD" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ONLINERECORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."ONLINERECORD_PK" ON "CITY"."ONLINERECORD" ("IDENTITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ONLINERECORD
--------------------------------------------------------

  ALTER TABLE "CITY"."ONLINERECORD" ADD CONSTRAINT "ONLINERECORD_PK" PRIMARY KEY ("IDENTITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CITY"."ONLINERECORD" MODIFY ("RECORD" NOT NULL ENABLE);
  ALTER TABLE "CITY"."ONLINERECORD" MODIFY ("IDENTITY" NOT NULL ENABLE);
