--------------------------------------------------------
--  文件已创建 - 星期一-六月-12-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ONLINEILLEGAL
--------------------------------------------------------

  CREATE TABLE "CITY"."ONLINEILLEGAL" 
   (	"IDENTITY" VARCHAR2(20 BYTE), 
	"JSON" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ONLINEILLEGAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."ONLINEILLEGAL_PK" ON "CITY"."ONLINEILLEGAL" ("IDENTITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ONLINEILLEGAL
--------------------------------------------------------

  ALTER TABLE "CITY"."ONLINEILLEGAL" ADD CONSTRAINT "ONLINEILLEGAL_PK" PRIMARY KEY ("IDENTITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CITY"."ONLINEILLEGAL" MODIFY ("IDENTITY" NOT NULL ENABLE);
  ALTER TABLE "CITY"."ONLINEILLEGAL" MODIFY ("JSON" NOT NULL ENABLE);
