--------------------------------------------------------
--  文件已创建 - 星期二-六月-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDYHISTORYRECORD
--------------------------------------------------------

  CREATE TABLE "CITY"."STUDYHISTORYRECORD" 
   (	"IDENTITY" VARCHAR2(20 BYTE), 
	"NOTICESTATUS" VARCHAR2(20 BYTE), 
	"STUDYSTATUS" VARCHAR2(20 BYTE), 
	"NOTICEDATE" DATE, 
	"SYNCDATE" DATE, 
	"STUDYSTARTDATE" DATE, 
	"STUDYCOMPLETEDATE" DATE, 
	"STOPLICENSE" VARCHAR2(1 BYTE), 
	"ORDINAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CITY"."STUDYHISTORYRECORD"."STOPLICENSE" IS '1，已经停止，0没有';
REM INSERTING into CITY.STUDYHISTORYRECORD
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index STUDYHISTORYRECORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."STUDYHISTORYRECORD_PK" ON "CITY"."STUDYHISTORYRECORD" ("IDENTITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDYHISTORYRECORD_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."STUDYHISTORYRECORD_PK1" ON "CITY"."STUDYHISTORYRECORD" ("ORDINAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger STUDYHISTORYRECORD_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CITY"."STUDYHISTORYRECORD_TRG" 
BEFORE INSERT ON STUDYHISTORYRECORD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ORDINAL IS NULL THEN
      SELECT STUDYHISTORYRECORD_SEQ.NEXTVAL INTO :NEW.ORDINAL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CITY"."STUDYHISTORYRECORD_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDYHISTORYRECORD
--------------------------------------------------------

  ALTER TABLE "CITY"."STUDYHISTORYRECORD" ADD CONSTRAINT "STUDYHISTORYRECORD_PK" PRIMARY KEY ("ORDINAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CITY"."STUDYHISTORYRECORD" MODIFY ("ORDINAL" NOT NULL ENABLE);
  ALTER TABLE "CITY"."STUDYHISTORYRECORD" MODIFY ("STUDYSTATUS" NOT NULL ENABLE);
  ALTER TABLE "CITY"."STUDYHISTORYRECORD" MODIFY ("NOTICESTATUS" NOT NULL ENABLE);
  ALTER TABLE "CITY"."STUDYHISTORYRECORD" MODIFY ("IDENTITY" NOT NULL ENABLE);
  ALTER TABLE "CITY"."STUDYHISTORYRECORD" MODIFY ("SYNCDATE" NOT NULL ENABLE);
