--------------------------------------------------------
--  文件已创建 - 星期五-四月-28-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "CITY"."USERS" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"LIMIT" VARCHAR2(1024 BYTE), 
	"DEPARTMENT" VARCHAR2(50 BYTE), 
	"POST" VARCHAR2(20 BYTE), 
	"POLICENUM" VARCHAR2(20 BYTE), 
	"REALNAME" VARCHAR2(20 BYTE), 
	"DISABLED" NUMBER(1,0) DEFAULT 1, 
	"PDA_TYPE" NUMBER, 
	"FIRSTFINGER" VARCHAR2(345 BYTE), 
	"SECONDFINGER" VARCHAR2(345 BYTE), 
	"COUNTYCODE" VARCHAR2(20 BYTE), 
	"AUTHORITYLEVEL" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CITY"."USERS"."USERNAME" IS '用户名';
   COMMENT ON COLUMN "CITY"."USERS"."PASSWORD" IS '密码';
   COMMENT ON COLUMN "CITY"."USERS"."LIMIT" IS '权限列表';
   COMMENT ON COLUMN "CITY"."USERS"."DEPARTMENT" IS '所属部门';
   COMMENT ON COLUMN "CITY"."USERS"."POST" IS '职务';
   COMMENT ON COLUMN "CITY"."USERS"."POLICENUM" IS '警员编号';
   COMMENT ON COLUMN "CITY"."USERS"."REALNAME" IS '警员姓名';
   COMMENT ON COLUMN "CITY"."USERS"."DISABLED" IS '是否已停用，0为停用，非零为正常用';
   COMMENT ON COLUMN "CITY"."USERS"."FIRSTFINGER" IS '拇指指纹';
   COMMENT ON COLUMN "CITY"."USERS"."SECONDFINGER" IS '食指指纹';
REM INSERTING into CITY.USERS
SET DEFINE OFF;
Insert into CITY.USERS (ID,USERNAME,PASSWORD,LIMIT,DEPARTMENT,POST,POLICENUM,REALNAME,DISABLED,PDA_TYPE,FIRSTFINGER,SECONDFINGER,COUNTYCODE,AUTHORITYLEVEL) values (108777307,'un11','QSS8CpM1wn8IbyS6IHpJEg==','{"123":true,"aa":false}',' ff','Audit','num','rn1',0,null,null,null,'hai','0');
Insert into CITY.USERS (ID,USERNAME,PASSWORD,LIMIT,DEPARTMENT,POST,POLICENUM,REALNAME,DISABLED,PDA_TYPE,FIRSTFINGER,SECONDFINGER,COUNTYCODE,AUTHORITYLEVEL) values (1317965796,'un','aa','{"yw28":true,"aa":false}',' ff','Audit','num','rn',0,null,null,null,'hai','0');
--------------------------------------------------------
--  DDL for Index USERSNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "CITY"."USERSNAME" ON "CITY"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "CITY"."USERS" MODIFY ("AUTHORITYLEVEL" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" MODIFY ("LIMIT" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" MODIFY ("DEPARTMENT" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" MODIFY ("POST" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" MODIFY ("POLICENUM" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" MODIFY ("REALNAME" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" MODIFY ("DISABLED" NOT NULL ENABLE);
  ALTER TABLE "CITY"."USERS" ADD CONSTRAINT "USERSNAME" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CITY"."USERS" MODIFY ("COUNTYCODE" NOT NULL ENABLE);
